### ISSUE TITLE
The page cannot be accessed.

### ISSUE THREAD

**Issue by newbie79** [junskr/iptime_tracker#1]
어느 날부터인가 갑자기 작동을 안해서 로그를 보니 제목과 같은 메시지가 출력되고 있습니다.
로그를 좀 추가해보니 아래와 같이 나오는데 어디를 수정해야 할지 모르겠습니다.

400, message="Invalid header value char:\n\n b'Content-type: text/plain; charset=utf-8'\n ^", url=URL('http://192.168.0.1/login/hostinfo2.cgi')

**Comment by junskr** [comment]
말씀하신 오류를 수정하여 1.4.0 버전을 배포합니다.
https://github.com/junskr/iptime_tracker/releases/tag/1.4.0
---

# ⚡ Bug fixed

- Fixed bugs related to the Mesh networks.
- HomeAssistant 버전 7.3부터 발생하던 에러 대응

##  :memo: 이하 상세

- HomeAssistant가 7.3으로 업데이트 되면서, Python과 aiohttp 라이브러리 버전이 업데이트 되었습니다.
- aiohttp 버전이 업데이트되면서, 비정상적인 HTTP Header를 읽을 수 없게끔 패치되었습니다.
- ipTIME 관리자페이지는 헤더에 비정상 문자가 포함되어 있습니다.
- 따라서 기존 async_get_clientsession를 이용하지 않고, 임의로 requests를 비동기 처리하도록 수정합니다.
