### ISSUE TITLE
iptime 3세대 UI beta

### ISSUE THREAD

**Issue by morendo9** [junskr/iptime_tracker#2]
https://iptime.com/iptime/?page_id=16&uid=25721&mod=document

iptime 관리 UI에 beta가 올라와 있는데 

지원할 계획이 있으신가요?

**Comment by juckee** [comment]
저도 beta UI 로 업데이트 이후에 작동을 안하네요. 지원해주시면 감사하겠습니다. ^^;;

**Comment by junskr** [comment]
저희집 제품(T3008)은 Beta UI 업데이트 지원을 하지 않네요 ^^ 곧 제품 구하는대로 업데이트 확인해보겠습니다.

**Comment by junskr** [comment]
Beta UI를 지원하도록 업데이트 하였습니다.
https://github.com/junskr/iptime_tracker/releases/tag/1.5.0
---

# ⚡ Updated to support Beta UI

- iptime 3세대 UI의 Beta 버전을 지원합니다.
- 현재 버전은 테스트 버전입니다.
- 지원 대상: A504NS-M
